### ISSUE TITLE
Unable to server raster versions of our vectors

### ISSUE THREAD

**Issue by jinky32** [klokantech/tileserver-gl#100]
Hi,

We are having problems getting our tile server to serve raster versions of our vectors for deviecs that require it.

Our mbtiles are generated from MapInfo files converted to GeoJSON using GDAL/OGR2OGR and then to mbtiles using tippecanoe. Within our tile server we are using a config.json file that has 5 vector sources like so:

`"outdoor800": {
            "url": "mbtiles://{outdoor800-data}",
            "type": "vector"
        }
`
and everything works perfectly for the vector versions, however when we try rendering raster tiles we can see something getting rendered on lower zoom levels (0 and 1) 

![0](https://cloud.githubusercontent.com/assets/932188/21636920/82aa8ee6-d25c-11e6-8e0c-7f910df1ad2e.png)

but higher than that I get blank screen over the uk and entries like these in the server output 

`GET /styles/coverage4Gand3G/rendered/2/3/1.png - - ms - -`

if we change the config.json file to have sources defined as raster like so
`"outdoor800": {
            "url": "mbtiles://{outdoor800-data}",
            "type": "raster"
        }`

we get the following in the server output:
`mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load tile 14/8580/5737=>14 for source composite: CGImageSourceCreateImageAtIndex failed' }
[Error: CGImageSourceCreateImageAtIndex failed]`

and

`GET /styles/coverage4Gand3G/rendered/16/34322/22950.png - - ms - -
GET /styles/coverage4Gand3G/rendered/16/34322/22951.png - - ms - -
[Error: CGImageSourceCreateImageAtIndex failed]
[Error: CGImageSourceCreateImageAtIndex failed]`

We have a few questions which may help us find our way through ths:

1) Does this error happen because our tile source has only vector data even though we have defined it as raster in the config?
2) Why do the raster tiles fail to render when the config file define the tile sources a vector?
3) Can you provide steps in order to render raster tiles from vector mbtiles source (assuming that this is possible)?
4) Is our conversion process (outlined above)  appropriate? In other words, is this process valid for serving raster tiles from a vector mbtiles source or do the mbtiles files need to be in a specific form and if yes how do we achieve this?

**Comment by klokan** [comment]
If your data are vector MBTiles, you must specify `type: vector` in the source in config.json.

> Does this error happen because our tile source has only vector data even though we have defined it as raster in the config?

Yes. Exactly.

> Why do the raster tiles fail to render when the config file define the tile sources a vector?

Very probably issue related to your JSON style or the data itself. We would need to review your config, style and data to debug this properly.

> Can you provide steps in order to render raster tiles from vector mbtiles source (assuming that this is possible)?

This is done automatically for valid source and style with TileServerGL, as described in the manual: 
http://tileserver.readthedocs.io/en/latest/endpoints.html#rendered-tiles

> Is our conversion process (outlined above) appropriate? In other words, is this process valid for serving raster tiles from a vector mbtiles source or do the mbtiles files need to be in a specific form and if yes how do we achieve this?

The suggested process sounds OK, but it is impossible to answer where the problem is without having additional information and access to sample data, config and style.

We suggest you get a support package from us, and provide us with samples.
Please contact info@klokantech.com. The discussion will continue there.
If the findings will result in modification of the TileServerGL code, we will reference this public ticket.
