### ISSUE TITLE
/fontstacks.json for maputnik

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#101]
The Maputnik editor can load the list of fonts from a fontstacks.json file similar to:

https://github.com/openmaptiles/fonts/blob/gh-pages/fontstacks.json

This can be generated by TileServerGL automatically.

Now it is only served under http://fonts.openmaptiles.org/ and it is a static file.

Next to that, TileServerGL does not serve fonts which are not used in any style (to protect the font files). Maybe implementation of fontstacks.json and removal of the font protection serving can be made together in one commit - as a single config option for public fontstacks.

There is no sponsor to implement this. A clean PR is welcome from the community.

**Comment by lukasmartinelli** [comment]
I don't think anyone from the community will implement this :)

At least the fontstacks.json is important #104 otherwise Maputnik doesn't show any fonts for all the OpenMapTiles styles (they now all switched to the public demo tileserver - question is how ideal is that).

Will fonts.openmaptiles.org still be active? If all styles point to the demo tileserver anyway?

**Comment by petrsloup** [comment]
I did this together with fixing some minor bugs and merging #104 .

@klokan 
It's now possible to add `"serveAllFonts": true` to `options` in config to serve all fontstacks from the fonts directory.
