### ISSUE TITLE
Endpoint with /style.json

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#154]
It may make sense to reconsider the endpoints exposed by the server.

TileJSON for /styles/{name}.json
GL Style JSON /styles/{name}/style.json
XYZ tiles at /styles/{name}/z/x/y.png

Then we are more aligned to GL Style Package spec and the way how we store GL styles in GitHub and zip files on releases, for example, https://github.com/openmaptiles/osm-bright-gl-style

Related to:
http://tileserver.readthedocs.io/en/latest/endpoints.html

To be discussed.

**Comment by petrsloup** [comment]
If we are going to make this change, it should be part of v2 since it breaks compatibility quite significantly (the `v2` branch already contains upgrade from node 4 to node 6.).

Notes:
- "GL Style JSON /styles/{name}/style.json" no problem
- "XYZ tiles at /styles/{name}/z/x/y.png" no problem
- "TileJSON for /styles/{name}.json" this is where the collision happens (and compatibility breaks)
  - v1 has style JSON on this URL
  - v2 will have TileJSON here
 
Solutions:
- a) Just change it
- b) Opt-in option (`newUrls: true`)
- c) Opt-out option (`legacyUrls: true`)

To be discussed.
