### ISSUE TITLE
Question ESRI Javascript API and WMTS

### ISSUE THREAD

**Issue by revenger73** [klokantech/tileserver-gl#16]
With tileserver-mapnik and tileserver-php WMTS is directly available as protocol, and we can use WMTS in ArcGIS Desktop and as WMTS Layer in a client web application based on ESRI Javascript API.

Does the tileserver-gl implementation offer WMTS support. And if not can i use the tileserver-gl as source in ESRI Javascript API (via VectorTileLayer or WebTiledLayer)?

**Comment by klokan** [comment]
The raster tiles produced by tileserver-gl can be used with OGC WMTS the same way as with our other tileserver projects, of course. All WMTS compatible clients are supported.

Technically it should be even possible to load the vector tiles directly as vectors (VectorTileLayer) in ESRI products, but an additional metadata needs to be exposed by the server.

The TileServer-GL is going to be announced and presented on FOSS4G 2016, it is now work in progress project.

We seek customers who are interested in these capabilities - to properly finish and document the open-source implementation. Would you be interested in contracting us on consulting for how to apply the project on your data?

**Comment by revenger73** [comment]
What is the endpoint to have TileServer-gl serve tiles as WMTS protocol. I tried /service? and /wmts but I looks like tileserver-gl does not (yet) have a WMTS endpoint?

Off course I can use MapProxy as extra layer (and to speed-up serving tiles by caching), but I was looking for a direct WMTS endpoint on tileserver-gl.

In ESRI Javascript API I was able to use the WebTiledLayer to connect to tileserver-gl. Have not yet tried using VectorTileLayer. Are there plans to provide samples on the index page with the VectorTileLayer? (like you have with tileserver-mapnik)

A last question....are there performance differences between tileserver-gl and tileserver-php?

As a web developer we currently use the osm2vectoriles mbtiles files to serve map data to our clients (we are not responsible for content). I have send your consulting question to the geo department.

**Comment by klokan** [comment]
Installing MapProxy just to make WMTS is not a good idea (you will proxy all the tiles and it kills the performance).

All what you need for WMTS to run is a single XML document (the endpoint), otherwise tiles from TileServerGL are compatible and ready to use.
This XML file can be created from TIleJSON generated by TileServer-GL already. Copy&paste the link to TileJSON into http://wmts.maptiler.com/ and you can open the tiles from TileServer-GL directly from all GIS clients, without a proxy for tiles. The same way it is done in tileserver-mapnik and if you host tiles on Amazon S3 or GCS or your own server without any software.

We may add the "WMTS" link directly to the user interface for raster tiles. Tracked under #17.

All the other questions or assistance with your workflow optimisation a map publishing  can be answered as part of One-to-One consulting. We would be glad to develop as part of contract also the ESRI VectorTileLayer support. Contact info@klokantech.com, please, if you are interested.

**Comment by revenger73** [comment]
Ok, thanks again for your quick response.

Actually in our current setup the extra MapProxy is quicker (but only off course after a tile is cached)

**Comment by revenger73** [comment]
Greetings! 

There is  something important I need to tell you, that you'd really like to hear, so please read it here <http://free.makeupbydaniellebrooke.com/e4byg>

Speak to you later, revenger

**Comment by revenger73** [comment]
Hi, 

I know you're gonna be  surprised by that news, just  take a look <http://above.mylanpro.com/e4bvmcfp>

Regards, revenger

**Comment by revenger73** [comment]
Hello! 

I've got a  really good  idea about how to spend my next weekend,  read more  here <http://thank.suggoirecords.com/e4gdmh>

Best regards, revenger

**Comment by wubet** [comment]
@revenger73 Would you please provide me some information how you configure/setup the mapProxy so that it cache the tileServer-gl?
