### ISSUE TITLE
Raster tile rendering bugs

### ISSUE THREAD

**Issue by hyperknot** [klokantech/tileserver-gl#161]
There are some buggy tile rendering with the raster renderer. For example:

http://demo.tileserver.org/styles/osm-bright/?raster#7/35.862/-121.371 (Monterey)
http://demo.tileserver.org/styles/klokantech-basic/?raster#2/18.0/18.5 (France)

I guess maybe a bigger rendering buffer would fix these issues. Would it be possible to make the rendering buffer configurable? (But it might not fix it, just an idea).

<img width="171" alt="screen shot 2017-05-13 at 01 15 24" src="https://cloud.githubusercontent.com/assets/494223/26019929/b2b9a6f8-3779-11e7-9355-e6a3ed88b22c.png">
<img width="161" alt="screen shot 2017-05-13 at 01 15 30" src="https://cloud.githubusercontent.com/assets/494223/26019930/b2d2d754-3779-11e7-84e1-8d08ffe8e9ca.png">

**Comment by BHudsonJSI** [comment]
I am seeing the same behaviour.  It only happens at certain levels, and usually when there is overlapping text like multiple POI, but not always as shown in the following screencap.  

![image](https://cloud.githubusercontent.com/assets/28735994/26116671/faddb39c-3a31-11e7-941f-46acaad97a8d.png)

Also sometimes happens when there is text that crosses tile borders.  e.g.:

From http://demo.tileserver.org/styles/osm-bright/?raster#15/45.3851/-75.6520
![image](https://cloud.githubusercontent.com/assets/28735994/26116749/3a17fefa-3a32-11e7-94d1-302c3c4cdfac.png)

The map data is accurate when displayed in vector format.

**Comment by petrsloup** [comment]
This is not possible to be fixed on the server. It's an issues of the data + style.

See https://github.com/klokantech/tileserver-gl/issues/35 and https://github.com/openmaptiles/openmaptiles/pull/191

**Comment by klokan** [comment]
This has been fixed in OpenMapTiles v3.5.
Issues with POIs on the deepzoom levels can be fixed by modifying the style https://github.com/openmaptiles/openmaptiles/issues/224

**Comment by hyperknot** [comment]
@klokan can you tell what is needed to use OMT 3.5?

1. Just git pulling the styles to the new version
2. Or I'd need to regenerate the whole planet unless on I'm on a commercial plan?
3. Is updating tileserver-gl needed?

**Comment by klokan** [comment]
1. - The style is not yet fixed. Ticket https://github.com/openmaptiles/openmaptiles/issues/224 is open - it tells what to do. Pull request ;-)?
2. - You need vector tiles with the v3.5+ schema. Render or purchase, or wait until we release the planet for free.
3. - No.
