### ISSUE TITLE
WMTS link for raster tiles

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#17]
The "WMTS" link for raster tiles is missing.

Either we link from JavaScript the wmts.maptiler.com service which turns the TileJSON to WMTS GetCapabilities XML, or we implement the correct XML serving on the server side directly.

**Comment by petrsloup** [comment]
Implemented as a link to wmts.maptiler.com.

Left to do:
- Use alternative character set when encoding base64 (`_` instead of `/`).

**Comment by petrsloup** [comment]
Done and deployed in v0.7

**Comment by spatialillusions** [comment]
Would be really nice if you could consider to implement the XML serving on the server side, would be really useful in cases where the server is running in an environment where it isn't possible to access maptiler.com. 
If you could give me some hints where it should be implemented I might be able to help out, but at the moment I'm not able to get the server running without installing the docker container because of missing dependencies, so it would be a bit like coding in the dark...
