### ISSUE TITLE
Is there any way render mbtiles from osm2vectortiles now?

### ISSUE THREAD

**Issue by songrui233** [klokantech/tileserver-gl#210]
I tried to install version 1.7 but failed.

**Comment by petrsloup** [comment]
The TileServer GL can use any tiles in MVT format packed in PBF, so it is still compatible with the discontinued osm2vectortiles.

However, the server only has built-in styles for OpenMapTiles (most common usecase), so if you only supply osm2vectortiles .mbtiles when launching, it gives you just the "inspect mode" to view the content of the tiles, because it has no styles for this structure of the data.

If you supply your own config.json file and styles when launching the server, it should still work.

**Comment by songrui233** [comment]
thanks a lot
