### ISSUE TITLE
No Text or place Name rendred

### ISSUE THREAD

**Issue by Namec** [klokantech/tileserver-gl#243]
Hello,

actually succeeded to run a TileServer Gl docker, and i have access to my vector tiles.

the probleme is there no names or any text rendered on the map.

is there any missing step in my installation ??

thank you

**Comment by hoenic07** [comment]
You probably are not hosting the fonts: http://tileserver.readthedocs.io/en/latest/config.html
Happened to me as well.
What URL do you have in your `glyphs` in your `style.json`?

**Comment by Namec** [comment]
trust it or not, but there is no style.json in all my server !!!

usually used path : usr/local/lib/.......

i found nothhing :-(

**Comment by hoenic07** [comment]
Then it seems that you don't have the fonts available locally. If you set the value of `glyphs` to `https://free.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}` it should work. If you want to use local fonts, have a look at the docs I posted above and follow the instructions to render the fonts (you need to do this first): https://github.com/openmaptiles/fonts

**Comment by Namec** [comment]
thank you for your help,

nothing i working, then i'll start from scratch and install the whole thing. (maybe i broke something)

sadly the openmaptiles have it's watermark even when i use my own mbtiles files !

**Comment by klokan** [comment]
I don't see any issue to be fixed in this TileServer GL repository. The links to documentation @hoenic07 provided are correct - there is no bug in this software and nothing to fix.

If our OpenMapTiles Server runs well for you - purchase the map tiles and you get a production ready-to-use mapping solution without watermarks. TileServer GL is only a rendering microservice component, which should be used in relation with tile caching, quantization and proper setup.

If you want to use the open-source project, you have to properly read the documentation, studt the source code and understand the principles of used components.

Free support may be available on Stackoverflow from the community - commercial support is available from authors of this software at https://openmaptiles.com/

**Comment by Namec** [comment]
You right, i will certainly switch to openmaptiles, as soon my product validated by my customer.

but you need to know, that out of the box no Font is rendered using the docker container.

Let the force be with you
