### ISSUE TITLE
Raster fonts don't render correctly when building from source in CentOS

### ISSUE THREAD

**Issue by ericsvendsen** [klokantech/tileserver-gl#245]
**- Clear description of the problem: What steps will lead to reproducing the error on our computer? What is exactly wrong?**
I built TileServer GL from source inside a CentOS 7 docker container, and the fonts don't render correctly (or at all, depending on the font) when viewing raster tiles.
**- Version of the TileServer GL software you have used**
Current source
**- Version and name of the operating system you use or other details of your setup**
Installing TileServer from source inside a CentOS 7 docker container.
**- Information about your used config / styles / vector tiles**
I'm using OpenStreetMap vector tiles from around Chicago, IL, USA, and fonts generated from the [openmaptiles/fonts project](https://github.com/openmaptiles/fonts). [Here's a gist](https://gist.github.com/ericsvendsen/bc1e111fe83814782dab9e73185d95f5) with my config, style, and the portion of my Dockerfile that's installing CentOS dependencies.

Is there a particular native dependency that handles raster fonts? When I install and run your Docker image with my config, everything works just fine. So I think I'm just missing a native dependency somewhere... 
![image](https://user-images.githubusercontent.com/1242132/34031947-cd9aaee6-e141-11e7-9b7a-d84de425acb8.png)

**Comment by hoenic07** [comment]
We had the same problem and couldn't fix it. My guess is that the wrong characters to render are calculated. If everything goes right mostly only the range from 0-255 of a font is requested by the server. But when using CentOS random font ranges are requested (e.g. in the ~50000 range)...
We had a look at the mapbox gl native code, but couldn't find the issue. A starting point could be: https://github.com/mapbox/mapbox-gl-native/blob/78545723fea953417e3de188e76cf92e8b6a67e4/src/mbgl/text/glyph_manager.cpp#L40
The bad thing is that Mapbox officially only supports Ubuntu and therefore won't help you a lot with fixing the issue.
So I think it's an issue with Mapbox GL native rather than TileServer GL

**Comment by ericsvendsen** [comment]
Ok, that's really good to know. Thanks for sharing your experience.

**Comment by zhali** [comment]
@ericsvendsen @hoenic07 i met the same problem with you, the Chinese font can't render correctly
CentOS7 + Tileserver-gl node version， the same code can do well on Unbutu

**Comment by hoenic07** [comment]
@ericsvendsen @zhali Please keep this thread up to date if you figure out a solution. I won't invest more time on this.

**Comment by zhali** [comment]
@hoenic07 ,i'm not sure it is because request wrong font ranges, can we open this issue for more guys to see it

**Comment by ericsvendsen** [comment]
@zhali since this appears to be a mapbox-gl-native thing, there's no reason from my perspective to keep this issue open here. Perhaps the best thing to do is submit a pull request for the docs ([as mentioned here](https://github.com/klokantech/tileserver-gl/issues/123#issuecomment-280082345)) to guide others and manage their expectations when trying to use CentOS.

@hoenic07 I'm with you - I haven't solved this problem and probably never will. I was able to clear the necessary red tape on my project to be able to use the Ubunu-based TileServer-GL docker image so I'm moving forward with that.

**Comment by zhali** [comment]
@ericsvendsen ok, i will submit a new request, in #123 @rmricw has use CentOS successfully
@hoenic07 i check the issue as you mentioned about request font ranges, but i m not sure it is the reason, because when use vector tile services ,the request font range number is also in the 0~50000, i would continue solve this issue , and if have any progress ，will tell you
