### ISSUE TITLE
Vector zoom 15 & 16 support 

### ISSUE THREAD

**Issue by peldhose** [klokantech/tileserver-gl#251]
First of all , thanks for the opensource mapserver. 
I think tileserver-gl not supporting manual zoom level support after 14 in vector maps.So will it be supported in future ???

**Comment by petrsloup** [comment]
TileServer-GL does not limit the zoom levels to level 14 - it depends on the data.

If you use OpenMapTiles, the vector tiles are currently created up to zoom level 14 (with 4096 internal resolution, so it can be rendered to 256x256 raster tiles up to zoom level 18).

Anyway, I'm closing this ticket, because it's probably a question about OpenMapTiles data (and belongs to https://github.com/openmaptiles/openmaptiles) and not about TileServer-GL.

**Comment by peldhose** [comment]
hi @petrsloup,
thank you for reply.
so can you help me to figure out which data should i use for getting zoom levels ??  
any provider or any work around ? ?

**Comment by petrsloup** [comment]
The zoom level 14 in OpenMapTiles data already contains all the data (all the buildings, POIs, etc.) and TileServer-GL uses this data to create raster tiles even in the higher zoom levels.

So if you request a raster tile at zoom level 16, it will use the proper tile from z14 and create the correct z16 for you.

**Comment by peldhose** [comment]
ya , my exact problem is to get z16 data on vector type from server, so that my app can render it properly,not raster Data.. 
is there any way to change os.pbf to .mbtiles to use with tileserver-gl ?

**Comment by petrsloup** [comment]
The OpenMapTiles project (https://github.com/openmaptiles/openmaptiles) is about the data processing (OSM -> PBF inside .mbtiles). See https://openmaptiles.com/support/ for details about support (and possibly custom cloud-based rendering with different parameters).

**Comment by klokan** [comment]
Your client should support overzooming of vector tiles. It is not a job for server...
