### ISSUE TITLE
How to run at Kubernetes?

### ISSUE THREAD

**Issue by strech345** [klokantech/tileserver-gl#258]
Hey,
this is not an issue and also not also about tileserver but maybe someone could help.

I want to run my files (mbtiles, styles,...) with the tileserver-gl docker image on kubernetes. Do i need to create an new image for example based on linux and run inside docker with this tileserver? Or - hopefully - is it possible to run it in a simple way?

**Comment by klokan** [comment]
> this is not an issue and also not also about tileserver

Ask at stackoverlow?

At @klokantech have done for our customers deployment scripts for Kubernetes. Available together with commercial support package: https://openmaptiles.com/support/

**Comment by bthuman** [comment]
bogus response

**Comment by bthuman** [comment]
I realize this is > 2 year old inquiry but I am looking for exactly the same thing -- trying to run tileserver-gl in Kubernetes especially since there appears to be performance issues with the basic implementation using Node.js under Docker.  Is there a different open source community where I should go versus being directed to commercial support?  And, why do you need scripts anyway?  YAML yes, but what scripts are you talking about?
