### ISSUE TITLE
node version limit in package.json

### ISSUE THREAD

**Issue by hanc2006** [klokantech/tileserver-gl#335]
This is more a technical question than a issue. Is there a reason why the node server version is limited?

>  "engines": {
    "node": ">=6 <7"
  },

I ask because I installed tileserver-gl with node server version 8.12 and I wanted to understand if the imposed node version limit in packages.json was connected to some performance problem encountered with the new version of node server.

Thank you

**Comment by petrsloup** [comment]
Before https://github.com/klokantech/tileserver-gl/pull/333, Node v8+ was not supported (missing precompiled binaries).

Now, node v8 might now be usable without any issues, but v6 is still better tested.

But we should update the package.json relatively soon if it turns out that everything is compatible with node v8.

**Comment by baptistemanson** [comment]
The unit tests are green.
In the current state, the lib doesn't install on macosx 10.9+ anymore:
- the latest canvas lib available for node 6 relies on libstd++ which is deprecated and not available.
We will be testing on node 10+ the lib and keep you posted!

**Comment by baptistemanson** [comment]
Under node 8 everything works. Unit tests and the the app with the demo data.

Under node 10, the rasterization segfaults due to https://github.com/mapbox/mapbox-gl-native/issues/12252
The rest is okay.

It is better NOT to upgrade past node 8.
