### ISSUE TITLE
Error building an ARM docker image

### ISSUE THREAD

**Issue by raman4793** [klokantech/tileserver-gl#349]
Hi,
I had to build an ARM compatible docker image of your mapserver, I already noticed #49 but I am facing a different issue. I tried to run npm install locally on the ARM machine to have more control over debugging process and I came across

403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v4.0.0/node-v57-linux-arm64-Release.tar.gz

and this 403 is blocking further npm installation, is it possible to help me out with this issue?

**Comment by petrsloup** [comment]
The same thing is still true -- ARM is not supported. Underlying mapbox-gl-native does not have ARM builds at the moment -- that's why the dependency download fails. You can try to compile it yourself, but you will probably run into many issues.

**Comment by luandro** [comment]
Why is this closed is it hasn't been solved?

**Comment by acalcutt** [comment]
Like mentioned above, the original mapbox-gl-native did not have binaries for arm, so tileserver-gl couldn't run on that platform. I'd imagine this is why it was closed many years ago.

Starting with TileServer v4.1.1, we are using maplibre-gl-native 5.0.1-pre.6, which is the first release so add [binaries for macos-12 arm64](https://github.com/maplibre/maplibre-gl-native/releases/tag/node-v5.0.1-pre.6). With the new binaries, tileserver should run (without docker) on top of MacOS 12 arm64 provided all native dependencies are installed. It may still have trouble inside the docker unless you build it for amd64 with, since there is no binary available for linux arm64. you need to build with
`docker buildx build --platform linux/amd64 -t tileserver-gl .` if you want to run the docker as is

**Comment by acalcutt** [comment]
I'd imagine if you run it without docker, in addition to the packages mentioned on https://tileserver.readthedocs.io/en/latest/installation.html#npm 

You may need some of these
`brew install glfw libuv`

**Comment by luandro** [comment]
In case I really need it for Docker, but good to know it's on it's way. I've managed to build [tileserver-gl-light](https://www.npmjs.com/package/tileserver-gl-light) for Docker arm64. I'll wait on the development of this to try and build tileserver-gl.

Thank you for the updates @acalcutt!

**Comment by luandro** [comment]
This works: https://hub.docker.com/r/wifidb/tileserver-gl/tags

**Comment by acalcutt** [comment]
I theory, arm64 support should now be included in maptiler/tileserver-gl:v4.3.2 . Can anyone still interested in this give it a test.
