### ISSUE TITLE
Broken map labeling spanning multiple raster tiles

### ISSUE THREAD

**Issue by procogent** [klokantech/tileserver-gl#35]
Map label elements that span multiple raster tiles are frequently cut off (only appearing on one of the tiles) resulting in odd artifacts.

![z10 example](https://cloud.githubusercontent.com/assets/20845025/17414566/c3368b30-5a3a-11e6-925d-faa3496ccdf4.png)
![z11 example](https://cloud.githubusercontent.com/assets/20845025/17414567/c33755b0-5a3a-11e6-8f7d-aeb14a891b6a.png)

**Comment by klokan** [comment]
Acknowledged. We will discuss how to increase the buffers around tiles to avoid this glitches.

**Comment by klokan** [comment]
We start to work actively on this issue. Upgrade of Mapbox GL Native did not solve the problem.
The next step is digging into the combination of input data (vector tiles + JSON style) on the sample area and debug tests on the GL Native.

**Comment by petrsloup** [comment]
I did some testing and it's possible there are actually two separate issues:
![image](https://cloud.githubusercontent.com/assets/707817/18049518/10d61092-6de9-11e6-86d0-594087433912.png)

- Sometimes, two labels are present very close to each other in both tiles, but it looks like different label is chosen to be used in different tile (blue circles).
- And sometimes the label is present only in one of the tiles and not the other (blue circle).

Since this issues is also happening when using mapbox-gl-native directly (center+zoom+dimensions), there is probably nothing we can do on tileserver-gl side -- it's either bug in mapbox-gl-native or the data.

We will look into the tiles data to better understand what exactly is going on.

**Comment by klokan** [comment]
Related PR: https://github.com/mapbox/mapbox-gl-native/pull/3357

**Comment by klokan** [comment]
@petrsloup - config for "MapMode::Still"?

**Comment by mikemorris** [comment]
This appears like you're hitting https://github.com/mapbox/mapbox-gl-native/issues/3582, which can be fixed by adding `symbol-avoid-edges: true` to the clipped label layer in the style. We're [considering making this default behavior](https://github.com/mapbox/mapbox-gl-style-spec/issues/287), would appreciate any feedback you have, or edge cases that this fails to address.

**Comment by petrsloup** [comment]
This indeed seems to help. Adding `"symbol-avoid-edges": true` to the affected layer ensures the labels are not rendered when touching the tile edge:
![image](https://cloud.githubusercontent.com/assets/707817/18242455/ae42ce52-7356-11e6-978c-86103d5c070c.png)
But it also removes some labels which were rendered correctly (such as "Fremont" or "Harbor Island").

However, it needs to be used carefully, since adding it to all layers removes unnecessarily many features (such as roads, etc.), which work correctly on the edges:
![image](https://cloud.githubusercontent.com/assets/707817/18242434/98809c52-7356-11e6-8261-7fadfa01c7e8.png)

**Comment by beikehanbao23** [comment]
I've the same problem,text lable spanning multiple raster tiles.

is there a metatile  before export tiles in mapbox-gl-native ? like  geowebcache?

**Comment by petrsloup** [comment]
There is currently nothing to be done on the server side.

This is more about the preparation of the data (tuning buffer sizes) and styles (sensible font sizes etc.).

**Comment by muesliq** [comment]
This might (still) be a Mapbox GL Native bug: https://github.com/mapbox/mapbox-gl-native/issues/11838
