### ISSUE TITLE
SVG output? 

### ISSUE THREAD

**Issue by muesliq** [klokantech/tileserver-gl#80]
Would it be possible to have Tileserver GL render results as SVGs instead of PNGs? 

Ideally SVGs would come layered (layers from stylesheet) to support editing in Adobe Illustrator or Inkscape.

**Comment by klokan** [comment]
No, unfortunately not - because it uses MapBox GL Native library which draws only raster data with OpenGL shaders. You can render at HighDPI if you target print output, but you don't get vector tile output now. The implementation of fonts in MapBox GL is raster only.

There are libraries which can generate GeoJSON from vector tiles - see #78.
GeoJSON can be styled in OpenLayers or Leaflet or other libraries - and OpenLayers can also load GL JSON styles now with an external library - so you could theoretically push it ;-). Would be a great project...

There is an online service which allows you to export our OSM2VectorTiles into vector data with basic styling as vectors including SVG via Leaflet - see http://hanshack.com/mapxtract/

**Comment by muesliq** [comment]
Thanks! So I guess we have to nag Mapbox then ;-)
