### ISSUE TITLE
docker with multiple MBTiles

### ISSUE THREAD

**Issue by lucasvw** [klokantech/tileserver-gl#82]
Hi, 

How would I go about hosting a tileserver with multiple mbtiles, for example. If I want to host the whole of Europe, I need all the individual country mbtiles.

Can I pass to the docker container a variable to make sure it uses all mbtiles? Now it just picks the first it finds in the directory.

Best,
Lucas

**Comment by klokan** [comment]
Hi Lucas,

you must generate your own config.json and place it in the `/data` volume next to your MBTiles.

See the manual for more details http://tileserver.readthedocs.io/, esp. http://tileserver.readthedocs.io/en/latest/config.html

**Comment by lucasvw** [comment]
Thanks! 

Ill give it a try!

**Comment by leye0** [comment]
I'm not sure how it tells anything about serving multiple mbtiles, though. @lucasvw Do you remember if you happen to have successfully served multiple mbtiles. Which would make sense as mapbox supports composite sources. Ex:
`"sources": {
    "mapbox": {
      "type": "vector",
      "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
    }
  },`

**Comment by iamlukesky** [comment]
I would like some pointers on this as well. I have my package.json and styling working, now I want to use multiple mbtiles for different areas, but apply the same styling to them.

**Comment by leye0** [comment]
In my case, the request would be to be able to switch between mbtiles selection based on a coordinates bounding box. Since with different tiles generator it is already possible to define a bounding box for what should be included in a .mbtiles database, that would be interesting to use this same bounding box  to tell the server to switch to different tiles. Is that possible with the current state of the code?
