### ISSUE TITLE
v1.3.0 docker image not loading mbtiles file

### ISSUE THREAD

**Issue by rjbaker** [klokantech/tileserver-gl#96]
Hi there,

I'm not sure if this is related to the recent v1.3.0 release. I have been using `klokantech/tileserver-gl:latest` and recently updated the docker image. This caused tileserver-gl to fail to load my local mbtiles, complaining that it's not in "openmaptiles" format.

```
$ docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl
Starting tileserver-gl v1.3.0-beta.1
No MBTiles specified, using london_england.mbtiles
Automatically creating config file for london_england.mbtiles
WARN: MBTiles not in "openmaptiles" format. Serving raw data only...
Run with --verbose to see the config file here.
Starting server
Listening at http://:::80/
```

Reverting to `docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl:v1.2.0` works fine:
```
Starting tileserver-gl v1.2.0
No MBTiles specified, using london_england.mbtiles
Automatically creating config file for london_england.mbtiles
Run with --verbose to see the config file here.
Starting server
Listening at http://:::80/
```

**Comment by klokan** [comment]
Expected behavior.

It is not a best practice to use the "latest" tag on production deployments - use specified version and test before upgrade.

If you have your own config.json back compatibility is preserved.

There are many improvements in 1.3.0 release and the change on OSM2VectorTiles must be done because of https://github.com/osm2vectortiles/osm2vectortiles/issues/387

**Comment by rjbaker** [comment]
Sorry I should have specified, this is currently in development and the instructions provided in the readme for use with docker will pull the latest image anyway.
